#cloud-config
package_update: true
packages:
  - git
  - python3
  - python3-venv

write_files:
  - path: /etc/motd
    permissions: "0644"
    content: |
      You are inside Capsule VM

runcmd:
  - mkdir -p /home/ubuntu/work
  - chown -R ubuntu:ubuntu /home/ubuntu/work

final_message: |
  capsule-vm sandbox ready.
