[build]
target-dir = "../../target"

[target.bpfel-unknown-none]
runner = "bpf-linker"
rustflags = [
  "-C", "panic=abort",
  "-C", "strip=debuginfo",
]

[target.bpfeb-unknown-none]
runner = "bpf-linker"
rustflags = [
  "-C", "panic=abort", 
  "-C", "strip=debuginfo",
]
