
[workspace]
members = ["src/hello-ebpf-userspace", "src/hello-ebpf-kernelspace", "src/common"]
resolver = "2"

[workspace.dependencies]
aya = { version = "0.13" }
aya-log = "0.2"
log = "0.4"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "net", "signal", "time"] }
