services:
  ebpf-dev:
    build:
      context: .
      dockerfile: Dockerfile
      # Specify platform for M1 Mac compatibility
      platforms:
        - linux/arm64
        - linux/amd64
    container_name: capsule-ebpf
    
    # Explicit platform specification for M1 Mac
    platform: linux/arm64

    # Required privileges for eBPF development
    privileged: true

    # Mount workspace and kernel modules
    volumes:
      - .:/workspace
      - /lib/modules:/lib/modules:ro
      # Mount cargo cache to speed up builds
      - ebpf-cargo-cache:/root/.cargo

    # Interactive shell
    tty: true
    stdin_open: true

    working_dir: /workspace

    # eBPF development environment
    environment:
      - BPF_CLANG=clang
      - LLVM_SYS_180_PREFIX=/usr
      - CARGO_TARGET_DIR=/workspace/target

    # Essential capabilities for eBPF
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE

volumes:
  ebpf-cargo-cache:
