[package]
name = "capsule-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow   = "1.0.98"
blake3   = "1.8.2"
cap-std  = "3.4.4"
clap = "4.5.37"
hex = "0.4.3"
libc = "0.2.172"
seccompiler = "0.5.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"

[dev-dependencies]
assert_cmd = "2.0.17"
