# Cargo.toml
[package]
name = "capsule"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow   = "1.0.98"
blake3   = "1.8.2"
cap-std  = "3.4.4"
libc = "0.2.172"
predicates = "3.1.3"
seccompiler = "0.5.0"

[dev-dependencies]
assert_cmd = "2.0.17"
