[package]
name = "capsule-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow   = "1.0.98"
blake3   = "1.8.2"
cap-std  = "3.4.4"
seccompiler = "0.5.0"

[dev-dependencies]
assert_cmd = "2.0.17"

