#cloud-config
package_update: true
packages: [{{EXTRA_PACKAGES}}]
# ...
- path: /etc/motd
  content: |
    You are inside Dimension Shifter: {{VM_NAME}}
# ...
runcmd:
  # your static commands...
{{RUNCMD_EXTRA}}
final_message: |
  ds sandbox ready. Use: multipass shell {{VM_NAME}}
